//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemploHorarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignacion_horario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asignacion_horario()
        {
            this.Horario = new HashSet<Horario>();
        }
    
        public int Id_Asignacion { get; set; }
        public string Dia { get; set; }
        public System.TimeSpan HoraDesde { get; set; }
        public System.TimeSpan HoraHasta { get; set; }
        public int IdInstructor { get; set; }
        public int IdFicha { get; set; }
        public Nullable<int> HorasProgramadas { get; set; }
        public Nullable<int> HorasTotales { get; set; }
    
        public virtual Ficha Ficha { get; set; }
        public virtual Instructor Instructor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horario> Horario { get; set; }
    }
}
