//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemploHorarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetenciaHorario
    {
        public int Id { get; set; }
        public int Id_Horario { get; set; }
        public int IdFicha { get; set; }
        public int IdCompetencia { get; set; }
        public int DuracionTotalPlaneada { get; set; }
        public int HorasAsignadas { get; set; }
        public bool Pendiente { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual Competencia Competencia { get; set; }
        public virtual Ficha Ficha { get; set; }
        public virtual Horario Horario { get; set; }
    }
}
