//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemploHorarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Competencia()
        {
            this.HorarioInstructor = new HashSet<HorarioInstructor>();
            this.ResultadoAprendizaje = new HashSet<ResultadoAprendizaje>();
        }
    
        public int IdCompetencia { get; set; }
        public int IdPrograma { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> DuracionTotal { get; set; }
        public Nullable<bool> Pendiente { get; set; }
        public Nullable<int> HorasAsignadas { get; set; }
    
        public virtual Programa_Formacion Programa_Formacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorarioInstructor> HorarioInstructor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultadoAprendizaje> ResultadoAprendizaje { get; set; }
    }
}
