//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemploHorarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competencias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Competencias()
        {
            this.Resultado_aprendizaje = new HashSet<Resultado_aprendizaje>();
        }
    
        public int Id_Competencias { get; set; }
        public string Nombre_competencias { get; set; }
        public Nullable<int> Duracion_Competencia { get; set; }
        public Nullable<int> Id_Resultado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resultado_aprendizaje> Resultado_aprendizaje { get; set; }
    }
}
