//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemploHorarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diseño_Curricular
    {
        public int IdCompetencia { get; set; }
        public string Competencia { get; set; }
        public Nullable<int> Orden { get; set; }
        public string Resultado { get; set; }
        public Nullable<int> Duracion { get; set; }
        public Nullable<int> HrTrimI { get; set; }
        public Nullable<int> HrTrimII { get; set; }
        public Nullable<int> HrTrimIII { get; set; }
        public Nullable<int> HrTrimIV { get; set; }
        public Nullable<int> HrTrimV { get; set; }
        public Nullable<int> HrTrimVI { get; set; }
        public Nullable<int> HrTrimVII { get; set; }
        public Nullable<int> Total_Hr { get; set; }
        public string Prog { get; set; }
        public string Pend { get; set; }
        public Nullable<decimal> Porcentaje { get; set; }
        public int IdInstructor { get; set; }
        public Nullable<int> Id_Horario { get; set; }
        public Nullable<int> IdFicha { get; set; }
    
        public virtual Horario Horario { get; set; }
        public virtual Ficha Ficha { get; set; }
        public virtual Instructor Instructor { get; set; }
    }
}
