//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemploHorarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ficha
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ficha()
        {
            this.Asignacion_horario = new HashSet<Asignacion_horario>();
            this.Diseño_Curricular = new HashSet<Diseño_Curricular>();
            this.Horario = new HashSet<Horario>();
            this.HorarioInstructor = new HashSet<HorarioInstructor>();
            this.Ambiente = new HashSet<Ambiente>();
        }
    
        public int IdFicha { get; set; }
        public Nullable<int> CodigoFicha { get; set; }
        public Nullable<System.DateTime> FechaInFicha { get; set; }
        public Nullable<System.DateTime> FechaFinFicha { get; set; }
        public Nullable<int> NumAprenFicha { get; set; }
        public string JornadaFicha { get; set; }
        public bool EstadoFicha { get; set; }
        public Nullable<int> IdPrograma { get; set; }
        public Nullable<int> IdOferta { get; set; }
        public Nullable<int> Trimestre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asignacion_horario> Asignacion_horario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diseño_Curricular> Diseño_Curricular { get; set; }
        public virtual Oferta Oferta { get; set; }
        public virtual Programa_Formacion Programa_Formacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horario> Horario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorarioInstructor> HorarioInstructor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ambiente> Ambiente { get; set; }
    }
}
