//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemploHorarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Horario()
        {
            this.Diseño_Curricular = new HashSet<Diseño_Curricular>();
        }
    
        public int Id_Horario { get; set; }
        public Nullable<int> Año_Horario { get; set; }
        public int Trimestre_Año { get; set; }
        public Nullable<System.DateTime> Fecha_Creacion { get; set; }
        public int IdFicha { get; set; }
        public Nullable<int> Id_Asignacion { get; set; }
        public Nullable<int> IdInstructorLider { get; set; }
    
        public virtual Asignacion_horario Asignacion_horario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diseño_Curricular> Diseño_Curricular { get; set; }
        public virtual Ficha Ficha { get; set; }
        public virtual Instructor Instructor { get; set; }
    }
}
