//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemploHorarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorarioInstructor
    {
        public int IdHorarioInstructor { get; set; }
        public int IdInstructor { get; set; }
        public int IdFicha { get; set; }
        public string Competencia { get; set; }
        public string Resultado { get; set; }
        public string Dia { get; set; }
        public System.TimeSpan HoraDesde { get; set; }
        public System.TimeSpan HoraHasta { get; set; }
    
        public virtual Ficha Ficha { get; set; }
        public virtual Instructor Instructor { get; set; }
    }
}
