//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemploHorarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstructorResultado
    {
        public int IdResultado { get; set; }
        public int IdInstructor { get; set; }
        public bool EsPrincipal { get; set; }
    
        public virtual Instructor Instructor { get; set; }
        public virtual ResultadoAprendizaje ResultadoAprendizaje { get; set; }
    }
}
