//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemploHorarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultadoAprendizaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResultadoAprendizaje()
        {
            this.HorarioInstructor = new HashSet<HorarioInstructor>();
            this.InstructorResultado = new HashSet<InstructorResultado>();
            this.ResultadoTrimestres = new HashSet<ResultadoTrimestre>();
            this.ResultadoTrimestres1 = new HashSet<ResultadoTrimestre>();
            this.ResultadoAprendizajeHorarios = new HashSet<ResultadoAprendizajeHorario>();
        }
    
        public int IdResultado { get; set; }
        public int IdCompetencia { get; set; }
        public string Descripcion { get; set; }
        public int DuracionResultado { get; set; }
        public Nullable<bool> Pendiente { get; set; }
        public Nullable<int> HorasAsignadas { get; set; }
        public int Id_Horario { get; set; }
    
        public virtual Competencia Competencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorarioInstructor> HorarioInstructor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstructorResultado> InstructorResultado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultadoTrimestre> ResultadoTrimestres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultadoTrimestre> ResultadoTrimestres1 { get; set; }
        public virtual Horario Horario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultadoAprendizajeHorario> ResultadoAprendizajeHorarios { get; set; }
    }
}
