//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemploHorarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resultado_aprendizaje
    {
        public int Id_Resultado { get; set; }
        public string Descripcion { get; set; }
        public int IdInstructor { get; set; }
        public int Id_Competencia { get; set; }
    
        public virtual Competencias Competencias { get; set; }
        public virtual Instructor Instructor { get; set; }
    }
}
