//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemploHorarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultadoTrimestre
    {
        public int IdResultado { get; set; }
        public int TrimestreAcad { get; set; }
        public int HorasPlaneadas { get; set; }
        public int Horas { get; set; }
        public int IdFicha { get; set; }
    
        public virtual ResultadoAprendizaje ResultadoAprendizaje { get; set; }
        public virtual Ficha Ficha { get; set; }
    }
}
